### PR TITLE
$ html instead text

### PR DESCRIPTION
**Pull request by lfreneda**
Using html jquery method to set custom label to skip / next buttons.

So we can set HTML Escape Characters :D

( http://www.theukwebdesigncompany.com/articles/entity-escape-characters.php )

:dancers:

### CODE REVIEW

**Comment by lfreneda** [comment]
@xbsoftware hello?

**Comment by lfreneda** [comment]
@blackazaru can u merge? :fearful:

**Comment by asaskevich** [comment]
Thanks, but I think better to have something like this:
```js
var skipButton = step_data.skipButton;
var label = skipButton .html || skipButton.text || 'Skip';
$(".enjoyhint_skip_btn")[skipButton.html ? 'html' : 'text'](label);
```
So we can easily switch between `html` and plain `text`.
Anyway, thanks for this PL and idea :smile:

**Comment by lfreneda** [comment]
I can implement your suggestion in another PR if you want to. :innocent:

Will you publish a new version of bower package?

Btw, Enjoyhint is fucking awesome, very very nice work of yours :joy:

--

I have another suggestion:

- When some step element is not found on that page, just skip/ignore that step.
What do you think? Can I implement it?

**Comment by lfreneda** [comment]
@asaskevich :cold_sweat:

**Comment by asaskevich** [comment]
Hey, sorry for the delay! :)

Package version will be updated, but Bower checks updates automatically and grabs them.

Skipping for nonexistent items will be great, because at the current moment such items can break the behaviour of script, so you can implement it if you would like to do it :smile:

**Pull request merged**
