### PR TITLE
Enjoyhint responsive

### PR DESCRIPTION
**Pull request by Kattoor**
For my student job at a startup company (Salesflare) I had to use this library.
However, I had to make it responsive.

Added onSkip & onNext callbacks to EnjoyHint options.
Added resizing label, arrow, skipbutton and shape.
After resizing the enjoyhint_disable_events gets corrected.
Enjoyhint closes when an active dom element goes missing.

### CODE REVIEW

**Comment by adaniello** [comment]
Very nice, thanks
+1

**Comment by dephora** [comment]
Yes, thank you. 
+1

**Comment by Zonfer** [comment]
It's work. Thank you.

**Comment by IpHamza** [comment]
what about error in the console

**Pull request merged**
